ShopNow/ShopNow/ShopNow/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('products.urls')),

]

ShopNow/ShopNow/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('products.urls')),

]

ShopNow/cart/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [

    
    url(r'^add/(?P<id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    url(r'^remove/(?P<id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^cart/$', views.view, name='cart'),
    
]

ShopNow/products/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [

    url(r'^home/$',views.index, name='index'),
    url(r'^loggedin/$',views.index2, name='index2'),
    url(r'^details/',views.detail, name='detail'),
    url(r'^mobile/$',views.mobile, name='mobile'),
    url(r'^laptops/$',views.laptops, name='laptops'),
    url(r'^sports/$',views.sports, name='sports'),
    url(r'^fashion/$',views.fashion, name='fashion'),
    url(r'^electronics/$',views.electronics, name='electronics'),
    url(r'^search/$',views.search, name="search"),
    url(r'^buynow/',views.buynow, name="search"),
    url(r'^',include('Userform.urls')),
    url(r'^',include('cart.urls')),
  
]

ShopNow/ShopNow/products/models.py
from django.db import models

class Product(models.Model):
    pname = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    details = models.TextField()
    Price_A=models.IntegerField(null=True)
    image = models.CharField(max_length=1000,null=True)
    
    def __str__(self):
        return self.pname

ShopNow/cart/models.py
from django.db import models

# Create your models here.
from products.models import Product

class CartItem(models.Model):
	cart = models.ForeignKey('Cart', null=True, blank=True)
	product = models.ForeignKey(Product)
	total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	quantity = models.IntegerField(default=1)
	price = models.IntegerField(default=1)
	line_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
	def __unicode__(self):
		try:
			return str(self.cart.id)
		except:
			return self.product.title
class Cart(models.Model):
	
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	

	def __unicode__(self):
		return "Cart id: %s" %(self.id)

ShopNow/products/models.py
from django.db import models

class Product(models.Model):
    pname = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    details = models.TextField()
    Price_A=models.IntegerField(null=True)
    image = models.CharField(max_length=1000,null=True)
    
    def __str__(self):
        return self.pname

ShopNow/ShopNow/products/views.py
from django.shortcuts import render, HttpResponse
from .models import Product
from Userform.models import Customer, Order
# Create your views here.
def index(request):
    return render(request, 'products/home.html', {'Name' : 'Login/SignUp', 'Email' : 'NaN', 'Contact' : 'Nan', 'Address' : 'Nan' })

def index2(request):
    return render(request, 'products/home2.html',)

def mobile(request):
    products = Product.objects.filter(category='Mobiles')
    context = {'products': products}
    template = 'products/mobile.html'	
    return render(request, template, context)
def laptops(request):
    products = Product.objects.filter(category='Laptops')
    context = {'products': products}
    template = 'products/laptops.html'	
    return render(request, template, context)
def sports(request):
    products = Product.objects.filter(category='Sports')
    context = {'products': products}
    template = 'products/sports.html'	
    return render(request, template, context)
def fashion(request):
    products = Product.objects.filter(category='Fashion')
    context = {'products': products}
    template = 'products/fashion.html'	
    return render(request, template, context)
def electronics(request):
    products = Product.objects.filter(category='Electronics')
    context = {'products': products}
    template = 'products/electronics.html'	
    return render(request, template, context)
def search(request):
	
     q= request.GET['q']
	
     products = Product.objects.filter(pname=q)
     context = {'query': q, 'products': products}
     template = 'products/results.html'	
	
     return render(request, template, context)

def detail(request):
    q= request.GET['p']

    products = Product.objects.filter(pname=q)
    context = {'query': q, 'products': products}
    template = 'products/results.html'	
	
    return render(request, template, context)

def buynow(request):
    q= request.GET['p']
    email = request.GET.get('r','')
    print(email)
    data = Customer.objects.get(Email=email)
    name = data.Name
    address = data.Address
    contact = data.Contact
    state = data.State
    pincode = data.PinCode
    print(q)
    products = Product.objects.get(pname=q)
    print(products)
    pname = products.pname

    new_order = Order(ProductName=pname, Name=name, Email=email, Address=address, State=state, PinCode=pincode)
    new_order.save()

    return HttpResponse("<h1>Order placed Successfully</h1>")
    

ShopNow/products/views.py
from django.shortcuts import render, HttpResponse
from .models import Product
from Userform.models import Customer, Order
# Create your views here.
def index(request):
    return render(request, 'products/home.html', {'Name' : 'Login/SignUp', 'Email' : 'NaN', 'Contact' : 'Nan', 'Address' : 'Nan' })

def index2(request):
    return render(request, 'products/home2.html',)

def mobile(request):
    products = Product.objects.filter(category='Mobiles')
    context = {'products': products}
    template = 'products/mobile.html'	
    return render(request, template, context)
def laptops(request):
    products = Product.objects.filter(category='Laptops')
    context = {'products': products}
    template = 'products/laptops.html'	
    return render(request, template, context)
def sports(request):
    products = Product.objects.filter(category='Sports')
    context = {'products': products}
    template = 'products/sports.html'	
    return render(request, template, context)
def fashion(request):
    products = Product.objects.filter(category='Fashion')
    context = {'products': products}
    template = 'products/fashion.html'	
    return render(request, template, context)
def electronics(request):
    products = Product.objects.filter(category='Electronics')
    context = {'products': products}
    template = 'products/electronics.html'	
    return render(request, template, context)
def search(request):
	
     q= request.GET['q']
	
     products = Product.objects.filter(pname=q)
     context = {'query': q, 'products': products}
     template = 'products/results.html'	
	
     return render(request, template, context)

def detail(request):
    q= request.GET['p']

    products = Product.objects.filter(pname=q)
    context = {'query': q, 'products': products}
    template = 'products/results.html'	
	
    return render(request, template, context)

def buynow(request):
    q= request.GET['p']
    email = request.GET.get('r')
    print(email)
    data = Customer.objects.get(Email=email)
    name = data.Name
    address = data.Address
    contact = data.Contact
    state = data.State
    pincode = data.PinCode
    print(q)
    products = Product.objects.get(pname=q)
    print(products)
    pname = products.pname

    new_order = Order(ProductName=pname, Name=name, Email=email, Address=address, State=state, PinCode=pincode)
    new_order.save()

    return HttpResponse("<h1>Order placed Successfully</h1>")
    

ShopNow/ShopNow/products/templates/products/contact.html
{% extends "products/header.html" %}
{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}

{% load crispy_forms_tags %}

<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>


{% block content %}
<h1><center>SIGN UP</center></h1>
<br>
<div class = "row">
<div class = "col-sm-4 col-sm-offset-4">

<form method='POST' action=''> {% csrf_token %}
{{ form|crispy }}
<input type='submit' value='submit form' class = 'btn btn-default' />
</form>
</div></div>

{% endblock %}

ShopNow/ShopNow/products/templates/products/electronics.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}

{% block content %}

 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
   <a id="home" href="/home" >Home</a>
  <a id="home2" href="/loggedin">Home</a>
 <a href="/mobile" >Mobiles</a>
  <a href="/laptops">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion">Fashion</a>
  <a href="/electronics" class="active">Electronics</a>
</div>
    </div>
<script>
	var name = sessionStorage.getItem('Name');
	
	if(name == 'Login/SignUp')
	{
	document.getElementById('home2').style.display = 'none';
		
	}
	else
	{
		document.getElementById('home2').style.display = 'block';
		document.getElementById('home').innerHTML = 'Logout';
}
</script>


<div>
    <div class="col-sm-9">
      <div class="row">
{% for product in products %}
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading" align="center">{{product.pname}}</div>
        <div class="panel-body"><center>
<a href="/details/?p={{product.pname}}"><img src="{{product.image}}"style="width:110px;height:160px;"alt="Image"></a></center></div>
        <div class="panel-footer">Price:{{product.Price_A}}<br>
</div>
	<center><a href="/details/?p={{product.pname}}" class="btn btn-info" >Buy</a></center>
<center><form class='form' method='POST' action='{% url "add_to_cart" product.id %}'> {% csrf_token %}
			 	 <input class='btn btn-default btn-block' type='submit' value='Add to cart'/></form>
</center>
  </div>
  </div>
{% endfor %}
</div>

</body>
</html>


{% endblock %}

ShopNow/ShopNow/products/templates/products/fashion.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}

{% block content %}

 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
   <a id="home" href="/home" >Home</a>
  <a id="home2" href="/loggedin">Home</a>
 <a href="/mobile" >Mobiles</a>
  <a href="/laptops">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion" class="active">Fashion</a>
  <a href="/electronics">Electronics</a>
</div>
    </div>
<script>
	var name = sessionStorage.getItem('Name');
	
	if(name == 'Login/SignUp')
	{
	document.getElementById('home2').style.display = 'none';
		
	}
	else
	{
		document.getElementById('home2').style.display = 'block';
		document.getElementById('home').innerHTML = 'Logout';
}
</script>


<div>
    <div class="col-sm-9">
      <div class="row">
{% for product in products %}
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading" align="center">{{product.pname}}</div>
        <div class="panel-body"><center>
<a href="/details/?p={{product.pname}}"><img src="{{product.image}}"style="width:110px;height:160px;"alt="Image"></a></center></div>
        <div class="panel-footer">Price:{{product.Price_A}}<br>
</div>
	<center><a href="/details/?p={{product.pname}}" class="btn btn-info" >Buy</a></center>
<center><form class='form' method='POST' action='{% url "add_to_cart" product.id %}'> {% csrf_token %}
			 	 <input class='btn btn-default btn-block' type='submit' value='Add to cart'/></form>
</center>
  </div>
  </div>
{% endfor %}
</div>

</body>
</html>


{% endblock %}

ShopNow/ShopNow/products/templates/products/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
  {% block script %} {% endblock %}
  </script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */ 
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }
    
    /* Remove the jumbotron's default bottom margin */ 
     .jumbotron {
      margin-bottom: 0;
    }
   
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
	
/*vertival menu*/

.vertical-menu {
    width: 200px;
}

.vertical-menu a {
    background-color: #eee;
    color: black;
    display: block;
    padding: 12px;
    text-decoration: none;
}

.vertical-menu a:hover {
    background-color: #ccc;
}

.vertical-menu a.active {
    background-color: #4CAF50;
    color: white;
}
  </style>
</head>
<body>

<div class="jumbotron">
  <div class="container text-center">
    <h1>ShopNow</h1>    
    <p>Mission, Vission & Values</p>

  </div>
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

         <li><a href="/mobile">Mobiles</a></li>
          <li><a href="/laptops">Laptops</a></li>
          <li><a href="/sports">Sports</a></li>
	<li><a href="/fashion">Fashion</a></li>
	<li><a href="/electronics">Electronics</a></li>

      </ul>
       <form class="navbar-form navbar-right"  input-group" action='/search/' method="get">
        <div class="form-group input-group">
          <input type="text" class="form-control" placeholder="Search.." id='searchbox' name="q">
               
        </div>
<button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/login" data-json = {'Name' : 'Login/SignUp'}><span class="glyphicon glyphicon-user"></span>{% block name %} {% endblock %}</a></li>
        <li><a href="/cart"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
      </ul>
    </div>
  </div>
</nav>

	{% block content %}
	{% endblock %}
</div>
</body>
</html>

ShopNow/ShopNow/products/templates/products/home.html
{% extends "products/header.html" %}

{% block name %}
{{ Name }}
{% endblock %}
	
{% block content %}



 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
  <a id='home' href="/home" class="active">Home</a>
  <a id='home2' href="/loggedin">Home</a>
  <a href="/mobile">Mobiles</a>
  <a href="/laptops">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion">Fashion</a>
  <a href="/electronics">Electronics</a>
  
</div>
    </div>

	<div>

<script>

	sessionStorage.setItem('Name', '{{Name}}');
	sessionStorage.setItem('Email', '{{Email}}');
	sessionStorage.setItem('Address', '{{Address}}');
	sessionStorage.setItem('Contact', '{{Contact}}');
	sessionStorage.setItem('Pincode', '{{PinCode}}');
	sessionStorage.setItem('State', '{{State}}');
	
	var name = sessionStorage.getItem('Name');
	
	if(name == 'Login/SignUp')
	{
	document.getElementById('home2').style.display = 'none';
	}
	else
	{
		
		document.getElementById('home2').style.display = 'block';
		document.getElementById('home').innerHTML = 'Logout';
		document.getElementById("home2").style.color = "#fff";
		document.getElementById("home").style.color = "#000";
		document.getElementById("home").style.backgroundColor = "#fff";
		document.getElementById("home2").style.backgroundColor = "#4BB051";		
	}
	</script>
	
<script>


</script>	
	<center>
    <div class="col-sm-9">
    <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-danger">
        <div class="panel-heading">SPECIAL DEAL</div>
        <div class="panel-body"><a href="/details/?p=Whirpool%20Refrigerator"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/71HZzXDKicL._SL1500_.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">Whirlpool Refrigerator</div>
      </div>
    </div>
    <div class="col-sm-6"> 
      <div class="panel panel-success">
        <div class="panel-heading">SPECIAL DEAL</div>
        <div class="panel-body"><a href="/details/?p=ManQ+Slim+Fit+Formal"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41nPyFoWCaL.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">ManQ Slim Fit Formal</div>
      </div>
    </div>
  </div>
<br>
   
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">AMAZING THURSDAY DEAL</div>
        <div class="panel-body"><a href="/details/?p=Dell+Inspiron"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41k5rlzMBFL.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">Dell Inspiron</div>
      </div>
    </div>
   
    <div class="col-sm-6"> 
      <div class="panel panel-primary">
        <div class="panel-heading">AMAZING THURSDAY DEAL</div>
        <div class="panel-body"><a href="/details/?p=Apple+MacBook+Air"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41GPeBcssaL.jpg" class="img-responsive" style="width:100%" height = 200px width = 200px alt="Image"></a></div>
        <div class="panel-footer">Apple MacBook Air</div>
      </div>
    </div>
  </div>
</div>
</div></div>
<br><br>
</center>
<footer class="container-fluid text-center">
  <p>Online Store Copyright</p>  
  <form class="form-inline">Get deals:
    <input type="email" class="form-control" size="50" placeholder="Email Address">
    <button type="button" class="btn btn-danger">Sign Up</button>
  </form>
</footer>


{% endblock %}

ShopNow/ShopNow/products/templates/products/home2.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}

	
{% block content %}



 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
  <a id='home' href="/home">Logout</a>
  <a id='home2' href="/loggedin"  class="active">Home</a>
  <a href="/mobile">Mobiles</a>
  <a href="/laptops">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion">Fashion</a>
  <a href="/electronics">Electronics</a>
  
</div>
    </div>
	
	<div>	
	
    <center>
    <div class="col-sm-9">
    <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-danger">
        <div class="panel-heading">SPECIAL DEAL</div>
        <div class="panel-body"><a href="/details/?p=Whirpool%20Refrigerator"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/71HZzXDKicL._SL1500_.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">Whirlpool Refrigerator</div>
      </div>
    </div>
    <div class="col-sm-6"> 
      <div class="panel panel-success">
        <div class="panel-heading">SPECIAL DEAL</div>
        <div class="panel-body"><a href="/details/?p=ManQ+Slim+Fit+Formal"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41nPyFoWCaL.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">ManQ Slim Fit Formal</div>
      </div>
    </div>
  </div>
<br>
   
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">AMAZING THURSDAY DEAL</div>
        <div class="panel-body"><a href="/details/?p=Dell+Inspiron"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41k5rlzMBFL.jpg" class="img-responsive" style="width:100%" alt="Image"></a></div>
        <div class="panel-footer">Dell Inspiron</div>
      </div>
    </div>
   
    <div class="col-sm-6"> 
      <div class="panel panel-primary">
        <div class="panel-heading">AMAZING THURSDAY DEAL</div>
        <div class="panel-body"><a href="/details/?p=Apple+MacBook+Air"><img style="width:110px;height:160px;" src="http://ecx.images-amazon.com/images/I/41GPeBcssaL.jpg" class="img-responsive" style="width:100%" height = 200px width = 200px alt="Image"></a></div>
        <div class="panel-footer">Apple MacBook Air</div>
      </div>
    </div>
  </div>
</div>
</div>
</center>



{% endblock %}

ShopNow/ShopNow/products/templates/products/laptops.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline;"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}

{% block content %}

 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
  <a id="home" href="/home" >Home</a>
  <a id="home2" href="/loggedin">Home</a>
  <a href="/mobile" >Mobiles</a>
  <a href="/laptops" class="active">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion">Fashion</a>
  <a href="/electronics">Electronics</a>
</div>
    </div>

<script>
	var name = sessionStorage.getItem('Name');
	
	if(name == 'Login/SignUp')
	{
	document.getElementById('home2').style.display = 'none';
		
	}
	else
	{
		document.getElementById('home2').style.display = 'block';
		document.getElementById('home').innerHTML = 'Logout';
		}
</script>

<div>	
    <div class="col-sm-9">
      <div class="row">
{% for product in products %}
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading" align="center">{{product.pname}}</div>
        <div class="panel-body"><center>
<a href="/details/?p={{product.pname}}"><img src="{{product.image}}"style="width:140px;height:160px;"alt="Image"></a></center></div>
        <div class="panel-footer">Price:{{product.Price_A}}<br>
</div>
	<center><a href="/details/?p={{product.pname}}" class="btn btn-info" >Buy</a></center>
<center><form class='form' method='POST' action='{% url "add_to_cart" product.id %}'> {% csrf_token %}
			 	 <input class='btn btn-default btn-block' type='submit' value='Add to cart'/></form>
</center>
  </div>
  </div>
{% endfor %}
</div>

</body>
</html>


{% endblock %}

ShopNow/ShopNow/products/templates/products/login.html
{% extends "products/header.html" %}
{% load crispy_forms_tags %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}


{% block content %}
<center><h1>LOGIN</h1></center>
<br>
<div class = "row">
<div class = "col-sm-4 col-sm-offset-4">

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method='POST' action=''> {% csrf_token %}
{{ form|crispy }}
<input type='submit' value='Login' class = 'btn btn-default' />
</form>
<center>
<a href="http://127.0.0.1:8000/signUp/">No Account yet? Create New Account</a></center>
</div></div>

{% endblock %}

ShopNow/ShopNow/products/templates/products/mobile.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	</script>
{% endblock %}


{% block content %}

 <div class="container-fluid">    
  <div class="row">
    <div class="col-sm-2 well">
     <div class="vertical-menu">
   <a id="home" href="/home" >Home</a>
  <a id="home2" href="/loggedin">Home</a>
 <a href="/mobiles" class="active">Mobiles</a>
  <a href="/laptops">Laptops</a>
  <a href="/sports">Sports</a>
  <a href="/fashion">Fashion</a>
  <a href="/electronics">Electronics</a>
</div>
    </div>
<script>
	var name = sessionStorage.getItem('Name');
	
	if(name == 'Login/SignUp')
	{
	document.getElementById('home2').style.display = 'none';
		
	}
	else
	{
		document.getElementById('home2').style.display = 'block';
		document.getElementById('home').innerHTML = 'Logout';
				
}
</script>


<div>
    <div class="col-sm-9">
      <div class="row">
{% for product in products %}
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading" align="center">{{product.pname}}</div>
        <div class="panel-body"><center>
<a href="/details/?p={{product.pname}}"><img src="{{product.image}}"style="width:110px;height:160px;"alt="Image"></a></center></div>
        <div class="panel-footer">Price:{{product.Price_A}}<br>
</div>
	<center><a href="/details/?p={{product.pname}}" class="btn btn-info" >Buy</a></center>
  </div>
  </div>
{% endfor %}
</div>

</body>
</html>


{% endblock %}

ShopNow/ShopNow/products/templates/products/results.html
{% extends "products/header.html" %}

{% block name %}
<p id='c' style="display:inline"><p>
<script>
	var name = sessionStorage.getItem('Name');
	document.getElementById('c').innerHTML = name;
	
	</script>
{% endblock %}


{% block content %}
<div style='padding:50px'>
<h1>Searched for: {{ query }}</h1>

{% for product in products %}
<h2>{{product.category}}</h2>
<img src="{{product.image}}" style="float:left;width:180px;height:300px;margin:30px;" > {{product.details|safe}}
<center><p style='margin:50px'><a  id='ma' href="/buynow/?p={{query}}&" class="btn btn-info" >Buy {{query}} at Rs. {{product.Price_A}}</a></p></center>

<script>

var email = sessionStorage.getItem('Email');

var url = '/buynow/?p={{product.pname}}&r=' + email;
document.getElementById('ma').href = url;
</script>
{% endfor %}

</div>
</body>
</html>


{% endblock %}

ShopNow/ShopNow/products/templates/products/view.html
{% extends "products/header.html" %}

{% block content %}

{% for item in cart.cartitem_set.all %}


{{ item.product }} {{ item.product.Price_A }}

<a href='{% url "remove_from_cart" item.id %}'>Remove</a>
{% endfor %}
{% endblock %}